# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Joel Correa'
tagline:          'Engineering Blog'
description:      '<a href="https://twitter.com/joelcorrea_" target="_blank">@joelcorrea_</a>'
url:              http://jjcorrea.github.io

author:
  name:           'Joel Correa'
  url:            https://twitter.com/joelcorrea_

paginate:         1

# Custom vars
version:          2.0.0

personal:
  linkedin: 'https://www.linkedin.com/profile/view?id=78338366'
  github: 'https://github.com/jjcorrea'

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'